---
name: Hello Workflow
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to Vikas
        run: echo "Hello Dosto"
      - name: Hello to Vikas
        run: echo "Hello $USER"
